import esbuild from "esbuild";
import process from "process";
import fs from "fs";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/`;

const prod = process.argv[2] === "production";

// The bundled dependencies contain dead-code <script> element creation:
//   - epub.js (Contents.addScript / Rendition.injectScript) — never reached
//     because this plugin never sets `settings.script` or calls addScript.
//   - setimmediate polyfill — only its legacy-IE branch builds a script; modern
//     Chromium/Electron uses the postMessage branch instead.
// Both trip static-analysis "dynamic script creation" checks. Rewrite the unused
// literals in the final bundle; runtime behavior is unchanged.
function stripDeadScriptLiterals() {
	const file = "main.js";
	const before = fs.readFileSync(file, "utf8");
	const after = before.replace(/createElement\((["'])script\1\)/g, 'createElement("template")');
	if (after !== before) fs.writeFileSync(file, after);
}

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	stripDeadScriptLiterals();
	process.exit(0);
} else {
	await context.watch();
}
